ACCOUNTABLE:
  NFT_PER_ACCOUNT_LIMIT: 3
APRIORI:
  AMOUNT_TO_STAKE:
  - 0.0001
  - 0.0003
BIMA:
  LEND: true
  PERCENT_OF_BALANCE_TO_LEND:
  - 20.0
  - 30.0
DEMASK:
  MAX_AMOUNT_FOR_EACH_ACCOUNT:
  - 1
  - 3
DISPERSE:
  MIN_BALANCE_FOR_DISPERSE:
  - 0.2
  - 0.5
FAUCET:
  CAPSOLVER_API_KEY: CAP-
FLOW:
  NUMBER_OF_SWAPS:
  - 1
  - 3
  PERCENT_OF_BALANCE_TO_SWAP:
  - 10
  - 15
GASZIP:
  AMOUNT_TO_REFUEL:
  - 0.0001
  - 0.00015
  MAX_WAIT_TIME: 999999
  MINIMUM_BALANCE_TO_REFUEL: 0.5
  NETWORKS_TO_REFUEL_FROM:
  - Arbitrum
  - Base
  - Optimism
  WAIT_FOR_FUNDS_TO_ARRIVE: true
KINTSU:
  AMOUNT_TO_STAKE:
  - 0.01
  - 0.02
LILCHOGSTARS:
  MAX_AMOUNT_FOR_EACH_ACCOUNT:
  - 1
  - 3
MAGICEDEN:
  NFT_CONTRACTS:
  - '0xb81fbb4362a586fdb3edfe261b2e1bbe73e6cd67'
  - '0x281df2c9178aa2dfd229771ef8f03cce90e60373'
  - '0x002c8fd766605b609d31cc9764e27289daf033e9'
  - '0x471af5eb201adc7851f4abec99ba1c78e51de0ce'
  - '0x63300257926af6f2a1bf2d4efb4240d8d8f250d6'
  - '0xfd3b54bd826cea09d15e87f95a869ecf3e462f92'
  - '0xb2ea0ff3ad4134367fb7dc75d48b3493e5a09c81'
  - '0x74e9115cfcaa5edbfc6670139c0b2a2833fc64ed'
  - '0xdecbb47872961d27275d68ae651e1956ef609f42'
MAGMA:
  AMOUNT_TO_STAKE:
  - 0.0001
  - 0.0003
MEMEBRIDGE:
  AMOUNT_TO_REFUEL:
  - 0.0001
  - 0.00015
  MAX_WAIT_TIME: 999999
  MINIMUM_BALANCE_TO_REFUEL: 0.5
  NETWORKS_TO_REFUEL_FROM:
  - Arbitrum
  - Base
  - Optimism
  WAIT_FOR_FUNDS_TO_ARRIVE: true
MONADKING:
  MAX_AMOUNT_FOR_EACH_ACCOUNT:
  - 1
  - 3
ORBITER:
  AMOUNT_TO_BRIDGE:
  - 0.1
  - 0.2
  BRIDGE_ALL: false
  MAX_WAIT_TIME: 999999999
  WAIT_FOR_FUNDS_TO_ARRIVE: true
SETTINGS:
  ACCOUNTS_RANGE:
  - 0
  - 0
  ATTEMPTS: 5
  BROWSER_PAUSE_MULTIPLIER: 1.5
  EXACT_ACCOUNTS_TO_USE: []
  PAUSE_BETWEEN_ATTEMPTS:
  - 5
  - 15
  PAUSE_BETWEEN_SWAPS:
  - 10
  - 40
  RANDOM_INITIALIZATION_PAUSE:
  - 1
  - 2
  RANDOM_PAUSE_BETWEEN_ACCOUNTS:
  - 3
  - 15
  RANDOM_PAUSE_BETWEEN_ACTIONS:
  - 3
  - 10
  TELEGRAM_BOT_TOKEN: ''
  TELEGRAM_USERS_IDS: []
  THREADS: 1
SHMONAD:
  BUY_AND_STAKE_SHMON: true
  PERCENT_OF_BALANCE_TO_SWAP:
  - 2
  - 3
  UNSTAKE_AND_SELL_SHMON: true
TESTNET_BRIDGE:
  AMOUNT_TO_REFUEL:
  - 0.0003
  - 0.0005
  MAX_WAIT_TIME: 999999
  MINIMUM_BALANCE_TO_REFUEL: 5.0
  NETWORKS_TO_REFUEL_FROM:
  - Arbitrum
  - Optimism
  WAIT_FOR_FUNDS_TO_ARRIVE: true
